# Generated by Django 6.0.5 on 2026-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bar', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_principal',
            field=models.CharField(choices=[('makeup', 'MAKEUP'), ('sexy_hot', 'SEXY - HOT'), ('fragance', 'FRAGANCE')], default='makeup', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(choices=[('ojos', 'OJOS'), ('labios', 'LABIOS'), ('piel', 'PIEL'), ('encajes', 'ENCAJES'), ('dulces', 'DULCES'), ('citricas', 'CÍTRICAS'), ('amaderadas', 'AMADERADAS')], default='piel', max_length=20),
        ),
    ]
