# Generated by Django 5.2.13 on 2026-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('comida', 'Comida'), ('otro', 'Otro')], default='bebida', max_length=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
