# Generated by Django 5.2.13 on 2026-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rosa_nieve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
