# Generated by Django 6.0.5 on 2026-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rosa_nieve', '0003_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(choices=[('ojos', 'OJOS'), ('labios', 'LABIOS'), ('piel', 'PIEL'), ('lenceria_sexy', 'LENCERÍA SEXY'), ('dulces', 'DULCES'), ('citricas', 'CÍTRICAS'), ('amaderadas', 'AMADERADAS')], default='piel', max_length=20),
        ),
    ]
